
#----------------------------------
# Novice
#----------------------------------

[BasicMastery]
Name = "Basic Mastery"
Icon = "nv_basic"
Target = "Passive"
MaxLevel = 8

[FirstAid]
Name = "First Aid"
Icon = "nv_firstaid"
Target = "Self"
MaxLevel = 1
SpCost = [4]

#----------------------------------
# Swordsman
#----------------------------------

[Bash]
Icon = "sm_bash"
Target = "Enemy"
MaxLevel = 10
SpCost = [8,8,8,8,8,15,15,15,15,15]
AdjustableLevel = true

[Endure]
Icon = "sm_endure"
Target = "Self"
MaxLevel = 10
SpCost = [1,2,3,4,5,6,7,8,9,10]

[IncreasedHPRecovery]
Name = "Improved HP Recovery"
Icon = "sm_recovery"
MaxLevel = 10
Target = "Passive"

[MagnumBreak]
Name = "Magnum Break"
Icon = "sm_magnum"
Target = "Self"
MaxLevel = 10
SpCost = [30,30,30,30,30,30,30,30,30,30]
AdjustableLevel = false

[Provoke]
Icon = "sm_provoke"
Target = "Enemy"
MaxLevel = 10
SpCost = [5,5,5,5,5,5,5,5,5,5]

[SwordMastery]
Name = "Sword Mastery"
Icon = "sm_sword"
Target = "Passive"
MaxLevel = 10

[TwoHandSwordMastery]
Name = "Two-Hand Sword Mastery"
Icon = "sm_twohand"
Target = "Passive"
MaxLevel = 10

#----------------------------------
# Mage
#----------------------------------

[IncreaseSPRecovery]
Name = "Improved Spiritual Recovery"
Icon = "mg_srecovery"
Target = "Passive"
MaxLevel = 10

[FireBolt]
Name = "Fire Bolt"
Icon = "mg_firebolt"
Target = "Enemy"
MaxLevel = 10
SpCost = [12,14,16,18,20,22,24,26,28,30]
AdjustableLevel = true

[ColdBolt]
Name = "Cold Bolt"
Icon = "mg_coldbolt"
Target = "Enemy"
MaxLevel = 10
SpCost = [12,14,16,18,20,22,24,26,28,30]
AdjustableLevel = true

[FireBall]
Name = "Fire Ball"
Icon = "mg_fireball"
Target = "Enemy"
MaxLevel = 10
SpCost = [25,25,25,25,25,25,25,25,25,25]
AdjustableLevel = true

[FireWall]
Name = "Fire Wall"
Icon = "mg_firewall"
Target = "Ground"
MaxLevel = 10
SpCost = [40,40,40,40,40,40,40,40,40,40]
AdjustableLevel = true

[FrostDiver]
Name = "Frost Diver"
Icon = "mg_frostdiver"
Target = "Enemy"
MaxLevel = 10
SpCost = [25,24,23,22,21,20,19,18,17,16]
AdjustableLevel = true

[LightningBolt]
Name = "Lightning Bolt"
Icon = "mg_lightningbolt"
Target = "Enemy"
MaxLevel = 10
SpCost = [12,14,16,18,20,22,24,26,28,30]
AdjustableLevel = true

[NapalmBeat]
Name = "Napalm Beat"
Icon = "mg_napalmbeat"
Target = "Enemy"
MaxLevel = 10
SpCost = [9,9,9,12,12,12,15,15,15,18]

[SoulStrike]
Name = "Soul Strike"
Icon = "mg_soulstrike"
Target = "Enemy"
MaxLevel = 10
SpCost = [18,14,24,20,30,26,36,32,42,38]
AdjustableLevel = true

[ThunderStorm]
Name = "Thunderstorm"
Icon = "mg_thunderstorm"
Target = "Ground"
MaxLevel = 10
SpCost = [29,34,39,44,49,54,59,64,69,74]
AdjustableLevel = true

[SafetyWall]
Name = "Safety Wall"
Icon = "mg_safetywall"
Target = "Ground"
MaxLevel = 10
SpCost = [30,30,30,35,35,35,40,40,40,40]
AdjustableLevel = true

[StoneCurse]
Name = "Stone Curse"
Icon = "mg_stonecurse"
Target = "Enemy"
MaxLevel = 10
SpCost = [25,24,23,22,21,20,19,18,17,16]

[Sight]
Name = "Sight"
Icon = "mg_sight"
Target = "Self"
MaxLevel = 1
SpCost = [10]

[EnergyCoat]
Name = "Energy Coat"
Icon = "mg_energycoat"
Target = "Self"
MaxLevel = 1
SpCost = [30]

#----------------------------------
# Archer
#----------------------------------

[DoubleStrafe]
Name = "Double Strafe"
Icon = "ac_double"
Target = "Enemy"
MaxLevel = 10
SpCost = [12,12,12,12,12,12,12,12,12,12]
AdjustableLevel = false

[ChargeArrow]
Name = "Charge Arrow"
Icon = "ac_chargearrow"
Target = "Enemy"
MaxLevel = 1
SpCost = [15]

[ArrowShower]
Name = "Arrow Shower"
Icon = "ac_shower"
Target = "Ground"
MaxLevel = 10
SpCost = [15,15,15,15,15,15,15,15,15,15]

[ImproveConcentration]
Name = "Improve Concentration"
Icon = "ac_concentration"
Target = "Self"
MaxLevel = 10
SpCost = [25,30,35,40,45,50,55,60,65,70]
AdjustableLevel = true

[OwlEye]
Name = "Owl's Eye"
Icon = "ac_owl"
Target = "Passive"
MaxLevel = 10

[VultureEye]
Name = "Vulture's Eye"
Icon = "ac_vulture"
Target = "Passive"
MaxLevel = 10

#----------------------------------
# Acolyte
#----------------------------------

[Heal]
Icon = "al_heal"
Target = "Ally"
MaxLevel = 10
SpCost = [13,16,19,22,25,28,31,34,37,40]
AdjustableLevel = true

[IncreaseAgility]
Name = "Increase Agility"
Icon = "al_incagi"
Target = "Ally"
MaxLevel = 10
SpCost = [18,21,24,27,30,33,36,39,42,45]
AdjustableLevel = true

[DecreaseAgility]
Name = "Decrease Agility"
Icon = "al_decagi"
Target = "Enemy"
MaxLevel = 5
SpCost = [17,21,25,29,33]

[Blessing]
Icon = "al_blessing"
Target = "Ally"
MaxLevel = 10
SpCost = [28,32,36,50,55,58,62,67,70,64]
AdjustableLevel = true

[DemonBane]
Name = "Demon Bane"
Icon = "al_demonbane"
Target = "Passive"
MaxLevel = 10

[DivineProtection]
Name = "Divine Protection"
Icon = "al_dp"
Target = "Passive"
MaxLevel = 10

[Angelus]
Name = "Angelus"
Icon = "al_angelus"
Target = "Self"
MaxLevel = 10
SpCost = [23,26,29,32,35,38,41,44,47,50]

[SignumCrusis]
Name = "Signum Crusis"
Icon = "al_crucis"
Target = "Self"
MaxLevel = 10
SpCost = [35,35,35,35,35,35,35,35,35,35]

[Cure]
Icon = "al_cure"
Target = "Ally"
MaxLevel = 1
SpCost = [15]

[AquaBenedicta]
Name = "Aqua Benedicta"
Icon = "al_holywater"
Target = "Self"
MaxLevel = 1
SpCost = [10]

[Pneuma]
Icon = "al_pneuma"
Target = "Ground"
MaxLevel = 1
SpCost = [10]

[Ruwach]
Icon = "al_ruwach"
Target = "Self"
MaxLevel = 1
SpCost = [10]

[Teleport]
Icon = "al_teleport"
Target = "Self"
MaxLevel = 2
SpCost = [11, 10]
AdjustableLevel = true

[WarpPortal]
Name = "Warp Portal"
Icon = "al_warp"
Target = "Ground"
MaxLevel = 4
SpCost = [35,32,29,26]
AdjustableLevel = false

[HolyLight]
Name = "Holy Light"
Icon = "al_holylight"
Target = "Enemy"
MaxLevel = 1
SpCost = [15]

#----------------------------------
# Thief
#----------------------------------

[DoubleAttack]
Name = "Double Attack"
Icon = "tf_double"
Target = "Passive"
MaxLevel = 10

[Envenom]
Icon = "tf_poison"
Target = "Enemy"
SpCost = [12,12,12,12,12,12,12,12,12,12]
MaxLevel = 10

[Detoxify]
Icon = "tf_detoxify"
Target = "Ally"
MaxLevel = 1
SpCost = [10]

[BackSlide]
Name = "Back Slide"
Icon = "tf_backsliding"
Target = "Self"
MaxLevel = 1
SpCost = [5]

[Steal]
Name = "Steal"
Icon = "tf_steal"
Target = "Enemy"
MaxLevel = 10
SpCost = [10,10,10,10,10,10,10,10,10,10]

[SandAttack]
Name = "Sand Attack"
Icon = "tf_sprinklesand"
Target = "Enemy"
MaxLevel = 1
SpCost = [9]

[ThrowStone]
Name = "Stone Fling"
Icon = "tf_throwstone"
Target = "Enemy"
MaxLevel = 1
SpCost = [2]

[FindStone]
Name = "Find Stone"
Icon = "tf_pickstone"
Target = "Enemy"
MaxLevel = 1
SpCost = [2]
#tf_pickstone

[Hiding]
Name = "Hiding"
Icon = "tf_hiding"
Target = "Self"
MaxLevel = 10
SpCost = [10,10,10,10,10,10,10,10,10,10]

[ImproveDodge]
Name = "Improve Dodge"
Icon = "tf_miss"
Target = "Passive"
MaxLevel = 10


#----------------------------------
# Merchant
#----------------------------------

[EnlargeWeightLimit]
Name = "Enlarge Weight Limit"
Icon = "mc_inccarry"
Target = "Passive"
MaxLevel = 10

[Discount]
Icon = "mc_discount"
Target = "Passive"
MaxLevel = 10

[Overcharge]
Icon = "mc_overcharge"
Target = "Passive"
MaxLevel = 10

[Vending]
Icon = "mc_vending"
Target = "Passive"
MaxLevel = 10
SpCost = [10,10,10,10,10,10,10,10,10,10]

[ItemAppraisal]
Name = "Item Appraisal"
Icon = "mc_identify"
Target = "Ally"
MaxLevel = 1

[Mammonite]
Icon = "mc_mammonite"
Target = "Enemy"
MaxLevel = 10
SpCost = [5,5,5,5,5,5,5,5,5,5]
AdjustableLevel = true

[PushCart]
Name = "Push Cart"
Icon = "mc_pushcart"
Target = "Passive"
MaxLevel = 1

[CrazyUproar]
Name = "Crazy Uproar"
Icon = "mc_loud"
Target = "Self"
MaxLevel = 1
SpCost = [8]

[CartRevolution]
Name = "Cart Revolution"
Icon = "mc_cartrevolution"
Target = "Enemy"
MaxLevel = 10
SpCost = [12,12,12,12,12,12,12,12,12,12]


#----------------------------------
# Other skills
#----------------------------------

[TwoHandQuicken]
Name = "Two-Hand Quicken"
Icon = "kn_twohandquicken"
Target = "Self"
MaxLevel = 10
SpCost = [14,18,22,26,30,34,38,42,46,50]

[Resurrection]
Name = "Resurrection"
Icon = "all_resurrection"
Target = "Ally"
MaxLevel = 4
SpCost = [60, 60, 60, 60]
InterruptMode = "InterruptOnDamage"

[HammerFall]
Name = "Hammer Fall"
Icon = "bs_hammerfall"
Target = "Ground"
MaxLevel = 5
SpCost = [10,10,10,10,10]

[SonicBlow]
Name = "Sonic Blow"
Icon = "as_sonicblow"
Target = "Enemy"
MaxLevel = 10
SpCost = [16,18,20,22,24,26,28,30,32,34]

#----------------------------------
# 2nd job skills
#----------------------------------

[EarthSpike]
Name = "Earth Spike"
[HeavensDrive]
Name = "Heavens Drive"
[JupitelThunder]
Name = "Jupitel Thunder"
[LordOfVermilion]
Name = "Lord of Vermilion"
[WaterBall]
Name = "Water Ball"
[Cloaking]

#----------------------------------
# Monster skills
#----------------------------------

[FireAttack]
Name = "Fire Attack"
[IceAttack]
Name = "Ice Attack"
[WaterAttack] 
Name = "Water Attack" #same as ice attack technically, used when the theme calls for it
[WindAttack]
Name = "Wind Attack"
[EarthAttack]
Name = "Earth Attack"
[DarkAttack]
Name = "Dark Attack"
[HolyAttack]
Name = "Holy Attack"
[PoisonAttack]
Name = "Poison Attack"
[UndeadAttack]
Name = "Undead Attack"
[GhostAttack]
Name = "Immaterial Attack"
[CriticalAttack]
Name = "Critical Slash"
[Curse]
Name = "Curse"
[Poison]
Name = "Poison"
[Sleep]
Name = "Sleep"
[Stun]
Name = "Stun"
[Blind]
Name = "Blind"
[Silence]
Name = "Silence"
[Petrify]
Name = "Petrify"

[FireBreath]
Name = "Fire Breath"
[IceBreath]
Name = "Ice Breath"
[WindBreath]
Name = "Wind Breath"
[EarthBreath]
Name = "Earth Breath"
[DarkBreath]
Name = "Dark Breath"
[HolyBreath]
Name = "Holy Breath"
[PoisonBreath]
Name = "Poison Breath"
[UndeadBreath]
Name = "Undead Breath"
[GhostBreath]
Name = "Immaterial Breath"

[SelfDestruct]
Name = "Self Destruct"
InterruptMode = "NoInterrupt"

[PowerUp]
Name = "Power Up"
InterruptMode = "NoInterrupt"

[SpeedUp]
Name = "Speed Up"
InterruptMode = "NoInterrupt"

[CallMinion]
Name = "Call Minion"
InterruptMode = "NoInterrupt"

[RecallMinion]
Name = "Recall"
InterruptMode = "NoInterrupt"

[SummonMonster]
Name = "Summon Monster"
InterruptMode = "NoInterrupt"

[Metamorphosis]
InterruptMode = "NoInterrupt"


[BloodDrain]
Name = "Blood Drain"
[EnergyDrain]
Name = "Energy Drain"
[GuidedAttack]
Name = "Guided Attack"
[SplashAttack]
Name = "Splash Attack"
[ComboAttack]
Name = "Combo Attack"
[PiercingAttack]
Name = "Piercing Attack"
[DarkStrike]
Name = "Dark Strike"
[BreakArmor]
Name = "Break Armor"
[BreakWeapon]
Name = "Break Weapon"
[BreakHelm]
Name = "Break Helm"
[DarkBlessing]
Name = "Dark Blessing"

[Smoking]
[Suicide]
[Stop]
[Hallucination]

[DarkThunder]
Name = "Dark Thunder"

#custom
[PharaohCurse]
Name = "Pharaoh's Curse"

[GrandThunderstorm]
Name = "Grand Thunderstorm"
InterruptMode = "NoInterrupt"

#used to show in skill prereqs
[QuestSkill]
Name = "Reward for Quest"

[Vampyrism]

[PhysBreaker] #originally Dark Breath (not to be confused with Darkness Breath, the aoe)
Name = "HP Breaker" #need to try to communicate it drops your maxHP...
[MentalBreaker]
Name = "Mental Breaker"

[NoCast]
#use when you want the enemy to trigger something without the player knowing
#use None instead if you want the skill flash to still show