
[Novice]
JobRank = 0
[Novice.SkillTree]
BasicMastery = []
FirstAid = [["BasicMastery", 8]]

[Swordsman]
JobRank = 1
Extends = "Novice"
[Swordsman.SkillTree]
SwordMastery = []
TwoHandSwordMastery = [["SwordMastery", 1]]
IncreasedHPRecovery = []
Bash = []
MagnumBreak = [["Bash", 5]]
Provoke = []
Endure = [["Provoke", 5]]
TwoHandQuicken = [["Bash", 10], ["Provoke", 5]] #just for testing

[Archer]
JobRank = 1
Extends = "Novice"
[Archer.SkillTree]
OwlEye = []
VultureEye = [["OwlEye", 3]]
DoubleStrafe = [["VultureEye", 10]]
ArrowShower = [["DoubleStrafe", 10]]
ImproveConcentration = [["VultureEye", 1]]
ChargeArrow = [["OwlEye", 10], ["VultureEye", 5]]

[Mage]
JobRank = 1
Extends = "Novice"
[Mage.SkillTree]
IncreaseSPRecovery = []
FireBolt = []
FireBall = [["FireBolt", 4]]
FireWall = [["FireBall", 5]]
LightningBolt = []
ThunderStorm = [["LightningBolt", 4]]
ColdBolt = []
FrostDriver = [["ColdBolt", 5]]
SoulStrike = []
SafetyWall = [["SoulStrike", 5]]

[Acolyte]
JobRank = 1
Extends = "Novice"
[Acolyte.SkillTree]
IncreaseSPRecovery = []
DivineProtection = []
DemonBane = [["DivineProtection", 1]]
Heal = []
Angelus = [["DivineProtection", 3]]
Blessing = [["DivineProtection", 5]]
IncreaseAgility = [["Heal", 3]]
DecreaseAgility = [["IncreaseAgility", 1]]
Cure = [["Heal", 2]]
Ruwach = []
Teleport = [["Ruwach", 1]]
WarpPortal = [["Teleport", 2]]
Pneuma = [["WarpPortal", 4]]
HolyLight = [["DemonBane", 5]]
SignumCrusis = [["DemonBane", 3]]
AquaBenedicta = []

[Thief]
JobRank = 1
Extends = "Novice"
[Thief.SkillTree]
DoubleAttack = []
ImproveDodge = []
Envenom = []
Detoxify = [["Envenom", 3]]
Steal = []
Hiding = [["Steal", 5]]
BackSlide = []
SandAttack = [["Envenom", 5]]
ThrowStone = []
SonicBlow = [["DoubleAttack", 10],["ImproveDodge",10]]

[Merchant]
JobRank = 1
Extends = "Novice"
[Merchant.SkillTree]
EnlargeWeightLimit = []
Discount = [["EnlargeWeightLimit",3]]
Overcharge = [["Discount",3]]
PushCart = [["EnlargeWeightLimit",5]]
Vending = [["PushCart",1]]
Mammonite = []
CrazyUproar = [["Mammonite", 3]]
ItemAppraisal = [["Discount",5]]



