
[Novice]
JobRank = 0
[Novice.SkillTree]
BasicMastery = []
FirstAid = [["BasicMastery", 2]]

[Swordsman]
JobRank = 1
Extends = "Novice"
[Swordsman.SkillTree]
SwordMastery = []
TwoHandSwordMastery = [["SwordMastery", 1]]
IncreasedHPRecovery = []
Bash = []
MagnumBreak = [["Bash", 5]]
Provoke = []
Endure = [["Provoke", 5]]
TwoHandQuicken = [["Bash", 10], ["Provoke", 5]] #just for testing

[Archer]
JobRank = 1
Extends = "Novice"
[Archer.SkillTree]
OwlEye = []
VultureEye = [["OwlEye", 3]]
DoubleStrafe = []
ArrowShower = [["DoubleStrafe", 10]]
ImproveConcentration = [["VultureEye", 1]]
ChargeArrow = [["OwlEye", 10], ["VultureEye", 5]]

[Mage]
JobRank = 1
Extends = "Novice"
[Mage.SkillTree]
IncreaseSPRecovery = []
FireBolt = []
FireBall = [["FireBolt", 4]]
FireWall = [["Sight", 1], ["FireBall", 5]]
LightningBolt = []
ThunderStorm = [["LightningBolt", 4]]
ColdBolt = []
FrostDiver = [["ColdBolt", 5]]
Sight = []
NapalmBeat = []
SoulStrike = [["NapalmBeat", 4]]
SafetyWall = [["NapalmBeat", 7], ["SoulStrike", 5]]
StoneCurse = []
#EnergyCoat = []

[Acolyte]
JobRank = 1
Extends = "Novice"
[Acolyte.SkillTree]
IncreaseSPRecovery = []
DivineProtection = []
DemonBane = [["DivineProtection", 1]]
Heal = []
Angelus = [["DivineProtection", 3]]
Blessing = [["DivineProtection", 5]]
IncreaseAgility = [["Heal", 3]]
#DecreaseAgility = [["IncreaseAgility", 1]]
#Cure = [["Heal", 2]]
Ruwach = []
Teleport = [["Ruwach", 1]]
Return = [["Teleport", 1]]
WarpPortal = [["Return", 1]]
Pneuma = [["WarpPortal", 4]]
HolyLight = [["DemonBane", 5]]
#SignumCrusis = [["DemonBane", 3]]
AquaBenedicta = []

[Thief]
JobRank = 1
Extends = "Novice"
[Thief.SkillTree]
DoubleAttack = []
ImproveDodge = []
Envenom = []
Detoxify = [["Envenom", 3]]
Steal = []
Hiding = [["Steal", 5]]
#SandAttack = [["Envenom", 5]]
BackSlide = [["ImproveDodge",5]]
#ThrowStone = [["QuestSkill",1]]
#FindStone = [["QuestSkill",1]]
SonicBlow = [["DoubleAttack", 5],["Envenom",10]]

[Merchant]
JobRank = 1
Extends = "Novice"
[Merchant.SkillTree]
EnlargeWeightLimit = []
Discount = [["EnlargeWeightLimit",3]]
Overcharge = [["Discount",3]]
PushCart = [["EnlargeWeightLimit",5]]
#Vending = [["PushCart",1]]
Mammonite = []
CrazyUproar = [["Mammonite", 3]]
CartRevolution = [["PushCart", 1], ["CrazyUproar", 1]]
#ItemAppraisal = [["Discount",5]]
HammerFall = []



