#
#Status Effects!
#
#Type = "Buff" or "Debuff". Used for targeting certain effects as well as positioning on the UI.
#CanDispel = if the buff can be lost by either dying or being targeted by dispel.
#CanDisable = if the player themselves can remove the status effect by right clicking the buff.

#----------------------------------
# General Negative Status Effects
#----------------------------------

[Curse]
Type = "Debuff"

[Stun]
Type = "Debuff"

[Frozen]
Type = "Debuff"

[Blind]
Type = "Debuff"

[Silence]
Type = "Debuff"

[Confusion]
Type = "Debuff"

[Poison]
Type = "Debuff"

[Petrifying]
Type = "Debuff"

[Stone]
Type = "Debuff"

[Provoke]
Type = "Debuff"

#----------------------------------
# Player Buffs
#----------------------------------

[PushCart]
Name = "Push Cart"
Type = "Buff"
CanDispel = false
CanDisable = false

[TwoHandQuicken]
Name = "Two-Hand Quicken"
Type = "Buff"
CanDispel = true
CanDisable = true

[Blessing]
Name = "Blessing"
Type = "Buff"
CanDispel = true
CanDisable = true

[IncreaseAgi]
Name = "Increase Agi"
Type = "Buff"
CanDispel = true
CanDisable = true

[Angelus]
Name = "Angelus"
Type = "Buff"
CanDispel = true
CanDisable = true

[SignumCrusis]
Name = "SignumCrusis"
Type = "Debuff"

[ImproveConcentration]
Name = "Improve Concentration"
Type = "Buff"
CanDispel = true
CanDisable = true

[Endure]
Name = "Endure"
Type = "Buff"
CanDispel = true
CanDisable = true

[MagnumBreak]
Name = "Magnum Break"
Type = "Buff"
CanDispel = true
CanDisable = true

[Pneuma]
Name = "Pneuma"
Type = "Buff"

[SafetyWall]
Name = "Pneuma"
Type = "Buff"

[Hiding]
Name = "Hiding"
Type = "Buff"
CanDispel = false
CanDisable = true

#----------------------------------
# Item Buffs
#----------------------------------

[IncreasedMoveSpeed]
Name = "Movement Speed UP"
Type = "Buff"
CanDispel = true
CanDisable = true

[IncreasedAttackSpeed]
Name = "Attack Speed UP"
Type = "Buff"
CanDispel = true
CanDisable = true

#----------------------------------
# Monster Status Effects
#----------------------------------

#Doom is used to kill monsters after a set period of time
[Doom]
Name = "Doom"
Type = "Debuff"
CanDispel = false
CanDisable = true
