#----------------------------------
# General Negative Status Effects
#----------------------------------

[Curse]
Type = "Debuff"

[Stun]
Type = "Debuff"

[Frozen]
Type = "Debuff"

[Blind]
Type = "Debuff"

[Silence]
Type = "Debuff"

[Confusion]
Type = "Debuff"

[Poison]
Type = "Debuff"

[Petrifying]
Type = "Debuff"

[Stone]
Type = "Debuff"

[Provoke]
Type = "Debuff"

#----------------------------------
# Player Buffs
#----------------------------------

[PushCart]
Name = "Push Cart"
Type = "Buff"
CanDispel = false
CanDisable = false

[TwoHandQuicken]
Name = "Two-Hand Quicken"
Type = "Buff"
CanDispel = true
CanDisable = true

[Blessing]
Name = "Blessing"
Type = "Buff"
CanDispel = true
CanDisable = true

[IncreaseAgi]
Name = "Increase Agi"
Type = "Buff"
CanDispel = true
CanDisable = true

[ImproveConcentration]
Name = "Improve Concentration"
Type = "Buff"
CanDispel = true
CanDisable = true

[Endure]
Name = "Endure"
Type = "Buff"
CanDispel = true
CanDisable = true