[TwoHandQuicken]
Name = "Two-Hand Quicken"
Type = "Buff"
CanDispel = true
CanDisable = true

[Blessing]
Name = "Blessing"
Type = "Buff"
CanDispel = true
CanDisable = true

[IncreaseAgi]
Name = "Increase Agi"
Type = "Buff"
CanDispel = true
CanDisable = true

[ImproveConcentration]
Name = "Improve Concentration"
Type = "Buff"
CanDispel = true
CanDisable = true

[Curse]
Name = "Curse"
Type = "Debuff"
CanDispel = true
CanDisable = false
